apiVersion: v1
kind: Service
metadata:
  name: xp-go-grpc-client-service
spec:
  selector:
    app: xp-go-grpc-client
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer